// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ80TaU8hP9Q7_zkPTFH2WGccg0nYm32g',
    appId: '1:451581113960:web:3c5ba6877e55cbd9b72ddd',
    messagingSenderId: '451581113960',
    projectId: 'gdg-solution-bugreapers',
    authDomain: 'gdg-solution-bugreapers.firebaseapp.com',
    storageBucket: 'gdg-solution-bugreapers.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt86pReFhAYR39aoj0Mer_Jt-MnL9OTY8',
    appId: '1:451581113960:android:2e143482cfd12b67b72ddd',
    messagingSenderId: '451581113960',
    projectId: 'gdg-solution-bugreapers',
    storageBucket: 'gdg-solution-bugreapers.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHPYF0j9p8JQ3daCMCLn_wv5V7jVHzzDE',
    appId: '1:451581113960:ios:8bf92de302af400ab72ddd',
    messagingSenderId: '451581113960',
    projectId: 'gdg-solution-bugreapers',
    storageBucket: 'gdg-solution-bugreapers.firebasestorage.app',
    iosBundleId: 'com.example.gdgSolution',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHPYF0j9p8JQ3daCMCLn_wv5V7jVHzzDE',
    appId: '1:451581113960:ios:8bf92de302af400ab72ddd',
    messagingSenderId: '451581113960',
    projectId: 'gdg-solution-bugreapers',
    storageBucket: 'gdg-solution-bugreapers.firebasestorage.app',
    iosBundleId: 'com.example.gdgSolution',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ80TaU8hP9Q7_zkPTFH2WGccg0nYm32g',
    appId: '1:451581113960:web:965c7d0cd54e372bb72ddd',
    messagingSenderId: '451581113960',
    projectId: 'gdg-solution-bugreapers',
    authDomain: 'gdg-solution-bugreapers.firebaseapp.com',
    storageBucket: 'gdg-solution-bugreapers.firebasestorage.app',
  );
}
